### ISSUE TITLE
Time estimate doesn't work for iterator scripts

### ISSUE THREAD

**Issue by JanGieseler** [LISE-B26/pylabcontrol#110]
I think this is due to having script with zero frequency that skrews up the estimation

**Comment by asafira** [comment]
I have tried a number of cases for loop and sweep scripts and they seem to work just fine --- I am going to keep trying more things (and move on to iter_nv and iter_points), but let me know if you know of a specific case where it goes wrong for loop or sweep scripts.

**Comment by JanGieseler** [comment]
Pulse blaster script was messed up but  should be fine now

**Comment by JanGieseler** [comment]
fixed
