### ISSUE TITLE
Gui: Saving fails with WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by akabcenell** [LISE-B26/pylabcontrol#134]
When saving to a good location (such as '\\\\?\\Z:/Lab/Lev/lab_measurements/20180323_sample_6/bead_1/cycle_3\\180402-19_41_11_takeimage'), saving fails in save_b26_file due to os.makedirs(os.path.dirname(filename)) failing on these filenames

**Comment by akabcenell** [comment]
The solution was to remove the \\\\?\\ that was automatically appended to the filepath. This happened just after moving to pyqt5. Unclear why that would cause this though.

**Comment by asafira** [comment]
I would prefer to close the issue if we can confirm that long save file names don't break...

**Comment by akabcenell** [comment]
This should be fixed by Script.check_filename, which should be called before all automatic saving in Script. If are the further problems, reopen this issue
