### ISSUE TITLE
master branch on alice has issues loading DAQ (missing DLL error)

### ISSUE THREAD

**Issue by emmarosenfeld** [LISE-B26/pylabcontrol#150]
![image](https://user-images.githubusercontent.com/29150475/42004270-20dbff1c-7a3d-11e8-82c4-37b17b13ed8d.png)

this happened when both loading the DAQ_Read_AI and ESR scripts (each one tried individually). That is all I tested so far on the master script and will go back to the old branch now

**Comment by asafira** [comment]
Unrelated, but it's pretty clear that we are once again printing quite a bit to standard out. Maybe it's time to clean up some of the print statements?

**Comment by JanGieseler** [comment]
what I like to do is to add an optional input to the functions `verbose` if True, you print a bunch to the std out, makes it easy to turn off the print statements and get them back quickly if needed

**Comment by akabcenell** [comment]
The config file in instruments had been deleted when switching branches. Restoring the config file fixed the issue.
