### ISSUE TITLE
when file path to be saved is too long, there is no relevant error message describing the issue

### ISSUE THREAD

**Issue by emmarosenfeld** [LISE-B26/pylabcontrol#154]
When you try to save a filename with a path that's too long, the following error message shows: 
![image](https://user-images.githubusercontent.com/29150475/42776770-0dc4add4-8906-11e8-8cab-873757a0ffeb.png)
Shortening the file name gets rid of this error, so I assume that's what calling the issue. It would be nice to show a message telling the user to shorten the filename + path.

**Comment by akabcenell** [comment]
Too long file names should now be properly recognized and the requisite '\\?\' prefix appended. If there are additional issues in the future, reopen this issue.
