### ISSUE TITLE
Instruments will not initialize if internal variables are created in __init__() before calling super()

### ISSUE THREAD

**Issue by asafira** [LISE-B26/PyLabControl#89]
Weird behavior was seen where SpectrumAnalyzer in b26_toolkit would not initialize because a variable was being created before super() was called.

**Comment by JanGieseler** [comment]
is this still an issue? I understand that if you create the variable before super() it doesn't cause any problems..
I tried to reproduce this issue with DummyInstrument, i.e. I created a variable before calling super() but this seems to work fine. Thus, it seems to be a specific issue with SpectrumAnalyzer 

**Question: should we close this issue?**

**Comment by JanGieseler** [comment]
move to b26_toolkit
