### ISSUE TITLE
API change for Script.get_script_information broke ScriptIterator for IterNVs and IterPoints

### ISSUE THREAD

**Issue by akabcenell** [LISE-B26/PyLabControl#92]
@JanGieseler: Script.get_script_information can no longer return a module when given just a class name. Should that be in the API, or is there another wanted solution? This breaks ScriptIterator lines 410, 415, etc.

**Comment by asafira** [comment]
We should probably write tests for Script Iterator to avoid this in the future.

**Comment by akabcenell** [comment]
Also ScriptIterator needs to keep its own index for tags when doing IterNVs (see line 177)
