### ISSUE TITLE
Cannot put same script twice in a loop

### ISSUE THREAD

**Issue by asafira** [LISE-B26/PyLabControl#99]
There are scenarios where it might be nice to put the same script twice in a loop or parameter sweep (maybe, for example, if you would like to FindNV another time inbetween data-taking scripts). It is not clear how to do that here, as the script disappears from the options once you move it into the script iterator box.

This is clearly possible if we could nest loop  and parameter sweep scripts, but that does not seem to be the case. Also, I think it would be cleaner to be able to do this.

**Comment by JanGieseler** [comment]
see issue #62
